/**
 * Copyright 2017-present, Callstack.
 * All rights reserved.
 *
 * @flow
 */

module.exports = {
  REQUEST_BUNDLE: 'REQUEST_BUILD',
  REQUEST_FILE: 'REQUEST_FILE',

  FILE_RECEIVED: 'FILE_RECEIVED',

  BUILD_START: 'BUILD_START',
  BUILD_FINISHED: 'BUILD_FINISHED',
  BUILD_FAILED: 'BUILD_FAILED',
  BUILD_PROGRESS: 'BUILD_PROGRESS',

  LIVE_RELOAD: 'LIVE_RELOAD',

  COMMUNICATION_ERROR: 'COMMUNICATION_ERROR',
};
